"""Equivalence tests: backend analysis must exactly match the frozen CLI pipeline.

These tests run the frozen linter pipeline directly and compare against the
backend adapter result.  Every test uses a temporary SQLite database.
"""

from __future__ import annotations

import os
import tempfile
import unittest
from pathlib import Path

from src.linter.evaluator import evaluate
from src.linter.parser import parse_requirements
from src.linter.reporter import render_report
from src.linter.rule_engine import run_checks

from backend.database import connect, init_db
from backend.linter_adapter import analyze_spec

SAMPLES_DIR = Path(__file__).resolve().parent.parent / "data" / "samples"
AMBIGUOUS_PATH = SAMPLES_DIR / "ambiguous-requirements.md"
CLEAN_PATH = SAMPLES_DIR / "clean-ears-requirements.md"


class EquivalenceTestBase(unittest.TestCase):
    """Base providing a temporary database."""

    def setUp(self) -> None:
        self._tmpdir = tempfile.TemporaryDirectory()
        self.db_path = os.path.join(self._tmpdir.name, "test.db")
        init_db(self.db_path)
        self.conn = connect(self.db_path)

    def tearDown(self) -> None:
        self.conn.close()
        self._tmpdir.cleanup()

    def _direct_pipeline(self, text: str):
        """Run the frozen linter pipeline directly."""
        records = parse_requirements(text)
        findings = run_checks(records)
        evaluation = evaluate(records, findings)
        return records, findings, evaluation


class AmbiguousEquivalenceTests(EquivalenceTestBase):
    """Backend must exactly match direct CLI pipeline for the ambiguous sample."""

    def test_counts_and_verdict_match(self) -> None:
        raw_text = AMBIGUOUS_PATH.read_text(encoding="utf-8")
        records, findings, evaluation = self._direct_pipeline(raw_text)

        result = analyze_spec(self.conn, "ambiguous-requirements.md", raw_text)

        self.assertEqual(result["requirement_count"], evaluation.requirement_count)
        self.assertEqual(len(result["findings"]), len(findings))
        self.assertEqual(result["defects"], evaluation.defects)
        self.assertEqual(result["clarifications"], evaluation.clarifications)
        self.assertEqual(result["infos"], evaluation.infos)
        self.assertEqual(result["score"], evaluation.score)
        self.assertEqual(result["tier"], evaluation.tier)
        self.assertEqual(result["verdict"], evaluation.verdict)
        self.assertEqual(result["exit_code"], evaluation.exit_code)

    def test_findings_identity_match(self) -> None:
        raw_text = AMBIGUOUS_PATH.read_text(encoding="utf-8")
        records, findings, evaluation = self._direct_pipeline(raw_text)

        result = analyze_spec(self.conn, "ambiguous-requirements.md", raw_text)

        # Each finding must match field-by-field
        for i, (backend_f, core_f) in enumerate(zip(result["findings"], findings)):
            self.assertEqual(backend_f["line_number"], core_f.line_number, f"finding {i} line_number")
            self.assertEqual(backend_f["type"], core_f.type, f"finding {i} type")
            self.assertEqual(backend_f["severity"], core_f.severity, f"finding {i} severity")
            self.assertEqual(backend_f["message"], core_f.message, f"finding {i} message")
            self.assertEqual(backend_f["suggested_rewrite"], core_f.suggested_rewrite, f"finding {i} suggested_rewrite")
            self.assertEqual(backend_f["check_id"], core_f.check_id, f"finding {i} check_id")
            self.assertEqual(backend_f["category"], core_f.category, f"finding {i} category")

    def test_report_markdown_contains_verdict_and_score(self) -> None:
        raw_text = AMBIGUOUS_PATH.read_text(encoding="utf-8")
        records, findings, evaluation = self._direct_pipeline(raw_text)

        result = analyze_spec(self.conn, "ambiguous-requirements.md", raw_text)

        # report_markdown must be generated by render_report
        self.assertIn("SpecBuddy Quality Report", result["report_markdown"])
        self.assertIn(f"**{evaluation.verdict}**", result["report_markdown"])
        self.assertIn(f"**{evaluation.score}/100**", result["report_markdown"])
        self.assertIn(f"Findings: {len(findings)}", result["report_markdown"])


class CleanEquivalenceTests(EquivalenceTestBase):
    """Backend must exactly match direct CLI pipeline for the clean sample."""

    def test_counts_and_verdict_match(self) -> None:
        raw_text = CLEAN_PATH.read_text(encoding="utf-8")
        records, findings, evaluation = self._direct_pipeline(raw_text)

        result = analyze_spec(self.conn, "clean-ears-requirements.md", raw_text)

        self.assertEqual(result["requirement_count"], evaluation.requirement_count)
        self.assertEqual(len(result["findings"]), len(findings))
        self.assertEqual(result["defects"], evaluation.defects)
        self.assertEqual(result["clarifications"], evaluation.clarifications)
        self.assertEqual(result["infos"], evaluation.infos)
        self.assertEqual(result["score"], evaluation.score)
        self.assertEqual(result["tier"], evaluation.tier)
        self.assertEqual(result["verdict"], evaluation.verdict)
        self.assertEqual(result["exit_code"], evaluation.exit_code)

    def test_findings_identity_match(self) -> None:
        raw_text = CLEAN_PATH.read_text(encoding="utf-8")
        records, findings, evaluation = self._direct_pipeline(raw_text)

        result = analyze_spec(self.conn, "clean-ears-requirements.md", raw_text)

        # Clean sample has 0 findings
        self.assertEqual(len(result["findings"]), 0)
        self.assertEqual(len(findings), 0)

    def test_report_markdown_contains_certified(self) -> None:
        raw_text = CLEAN_PATH.read_text(encoding="utf-8")
        records, findings, evaluation = self._direct_pipeline(raw_text)

        result = analyze_spec(self.conn, "clean-ears-requirements.md", raw_text)

        self.assertIn("SpecBuddy Quality Report", result["report_markdown"])
        self.assertIn("**CERTIFIED**", result["report_markdown"])
        self.assertIn("**100/100**", result["report_markdown"])
        self.assertIn("No findings", result["report_markdown"])


if __name__ == "__main__":
    unittest.main()
